Fix pygame.error: video system not initialized
When the activity is run outside Sugar, there is an error;

Traceback (most recent call last):
  File "jump.py", line 1011, in <module>
    main()
  File "jump.py", line 1008, in main
    MainWindow.SuperLooper()
  File "jump.py", line 630, in SuperLooper
    for event in pygame.event.get():
pygame.error: video system not initialized

Cause was port to sugargame.

Signed-off-by: James Cameron <quozl@laptop.org>